server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
